import math

print("파이 상수")
print("math.pi : ", math.pi)
print()
print("e 상수")
print("math.e : ", math.e)
print()
print("올림 - 3.5의 올림")
print("math.ceil(3.5)", math.ceil(3.5))
print()
print("내림 - 3.5의 내림")
print("math.floor(3.5)", math.floor(3.5))
print()
print("계승 구하기 - 5!(계승)")
print("math.factorial(5)", math.factorial(5))
print()
print("최대공약수 구ㅏ기 - 28과 70의 최대공약수")
print("math.gcd(28,70)", math.gcd(28, 70))
print()
